image: julia:1.0                # image comes from Docker hub

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  JULIA_DEPOT_PATH: "$CI_PROJECT_DIR/.julia/"

cache:
  paths:
    - .julia/

test:
  script:
    - julia --project=@. --color=yes -e "import Pkg; Pkg.test(; coverage = true)"
    - julia --project=test/coverage --color=yes -e 'import Pkg; Pkg.instantiate()'
    - julia --project=test/coverage --color=yes test/coverage/coverage_summary.jl
  only:
    - merge_requests
    - main
    - develop